### ISSUE TITLE
Poster thumbnail URL is missing KS when KS is provided

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/kaltura-player-js#263]
https://github.com/kaltura/kaltura-player-js/blob/263f91523d3581aba4e81e04bb90996a2627257a/src/ott/poster.js#L18

Should be constructed like this;
https://github.com/kaltura/kaltura-player-js/blob/master/src/common/utils/thumbs.js#L6 

Poster currently doesn't load if the Entry is set to Access Control that limits Thumbnail without KS.

**Comment by OrenMe** [comment]
Hi @zoharbabin, closing this issue as usage of KS for poster is under work by other teams.
