### ISSUE TITLE
Player is not working in localhost 

### ISSUE THREAD

**Issue by joaovinicius** [kaltura/kaltura-player-js#343]
Access to XMLHttpRequest at 'http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_c3k94ljx/name/a.mp4/index.m3u8' from origin 'http://localhost:9004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
logger.js:191 [Error] Category:1 | Code:1002 | 
{name: "levelLoadError", url: "http://cfvod2.kaltura.com/hls/p/2608811/sp/2608811…/2/ev/4/flavorId/0_c3k94ljx/name/a.mp4/index.m3u8", responseCode: 0}
xhr-loader.js:82 GET http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_c3k94ljx/name/a.mp4/index.m3u8 net::ERR_FAILED
876
Unchecked runtime.lastError: The message port closed before a response was received.
:9004/#/curso/718931…b058bdc006c1d3f79:1 Access to XMLHttpRequest at 'http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_slunqlq5/name/a.mp4/index.m3u8' from origin 'http://localhost:9004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
logger.js:191 [Error] Category:1 | Code:1002 | 
{name: "levelLoadError", url: "http://cfvod2.kaltura.com/hls/p/2608811/sp/2608811…/2/ev/4/flavorId/0_slunqlq5/name/a.mp4/index.m3u8", responseCode: 0}
xhr-loader.js:82 GET http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_slunqlq5/name/a.mp4/index.m3u8 net::ERR_FAILED
:9004/#/curso/718931…b058bdc006c1d3f79:1 Access to XMLHttpRequest at 'http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_bd19uznq/name/a.mp4/index.m3u8' from origin 'http://localhost:9004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
logger.js:191 [Error] Category:1 | Code:1002 | 
{name: "levelLoadError", url: "http://cfvod2.kaltura.com/hls/p/2608811/sp/2608811…/2/ev/4/flavorId/0_bd19uznq/name/a.mp4/index.m3u8", responseCode: 0}
xhr-loader.js:82 GET http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_bd19uznq/name/a.mp4/index.m3u8 net::ERR_FAILED
:9004/#/curso/718931…b058bdc006c1d3f79:1 Access to XMLHttpRequest at 'http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_c3k94ljx/name/a.mp4/index.m3u8' from origin 'http://localhost:9004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
logger.js:191 [Error] Category:1 | Code:1002 | 
{name: "levelLoadError", url: "http://cfvod2.kaltura.com/hls/p/2608811/sp/2608811…/2/ev/4/flavorId/0_c3k94ljx/name/a.mp4/index.m3u8", responseCode: 0}
xhr-loader.js:82 GET http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_c3k94ljx/name/a.mp4/index.m3u8 net::ERR_FAILED
:9004/#/curso/718931…b058bdc006c1d3f79:1 Access to XMLHttpRequest at 'http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_slunqlq5/name/a.mp4/index.m3u8' from origin 'http://localhost:9004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
logger.js:191 [Error] Category:1 | Code:1002 | 
{name: "levelLoadError", url: "http://cfvod2.kaltura.com/hls/p/2608811/sp/2608811…/2/ev/4/flavorId/0_slunqlq5/name/a.mp4/index.m3u8", responseCode: 0}
xhr-loader.js:82 GET http://cfvod2.kaltura.com/hls/p/2608811/sp/260881100/serveFlavor/entryId/0_zyffjvb7/v/2/ev/4/flavorId/0_slunqlq5/name/a.mp4/index.m3u8 net::ERR_FAILED

**Comment by OrenMe** [comment]
Hi @joaovinicius, you have CORS issue. Please contact your streaming provider and request them to add CORS headers on your stream.
I can reproduce the issue also on non localhost so this is not related to localhost.
